### ISSUE TITLE
[angular-ui-kit] TypeScript module resolution fails in v3.0.7 - Missing index.d.ts file

### ISSUE THREAD

**Issue by VictorIstrati** [dyte-io/ui-kit#127]
## Bug Description

When upgrading from @dytesdk/angular-ui-kit v2.x to v3.0.7, TypeScript fails to resolve the module with the following error:

```
error TS2307: Cannot find module '@dytesdk/angular-ui-kit' or its corresponding type declarations.

import { DyteComponentsModule } from '@dytesdk/angular-ui-kit';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Root Cause

The package.json file has conflicting type declaration paths:

```json
{
  "typings": "dist/index.d.ts",  // This file doesn't exist
  "exports": {
    ".": {
      "types": "./dist/dytesdk-angular-ui-kit.d.ts",  // This file exists
      // ...
    }
  }
}
```

## Environment

- @dytesdk/angular-ui-kit: 3.0.7
- @dytesdk/web-core: 3.1.4
- Angular: 15+
- TypeScript: 4.9+
- Node.js: 16+

## Reproduction Steps

1. Create a new Angular 15+ project
2. Install @dytesdk/angular-ui-kit@3.0.7
3. Import DyteComponentsModule from '@dytesdk/angular-ui-kit' in any module
4. Run `ng build`
5. Observe the TypeScript error
